### PR TITLE
Background mode

### PR DESCRIPTION
**Pull request by Relwi**
This PR is related to this [issue](https://github.com/libre-tube/LibreTube/issues/114).

A mode that allows the user to play the videos in the background, only with audio. Useful if you want to listen to music without wasting much data and loading times.

### CODE REVIEW

**Comment by Relwi** [comment]
I'm advancing little by little, these are the things that I have left to do (may be this list will be expanded in the future):

- [ ] Create the notification bar with the player controls
- [ ] When you select another video to run in background, stops the previous one
- [ ] When you close the app, keep the background mode running

**Comment by Bnyro** [comment]
Looks great so far :) When are you planning to finish it or is there anything we could do to help you?

**Comment by Relwi** [comment]
Thanks! Actually I don't have much time to develop this, a little bit help will be welcome, because idk how much time gonna take me to finish this alone.

**Comment by Bnyro** [comment]
Fine, I'm gonna try to help you a bit, but I can't promise you'll benefit from it xD

**Comment by janisslsm** [comment]
I'll give it a shot later today

**Comment by Bnyro** [comment]
I'm sorry for not helping you at the moment, I'm just busy with other stuff rn :/

**Comment by Relwi** [comment]
No problem @Bnyro , for now I'm fine, I can work on it in the weekends or when I have time

**Comment by Relwi** [comment]
Need to put a seekbar in the notification bar and should be done

**Comment by IceDBorn** [comment]
When the background mode is on, the videos you click should be played on the background player, not the foreground one.

**Comment by Bnyro** [comment]
> When the background mode is on, the videos you click should be played on the background player, not the foreground one.

@IceDBorn I think that this would only confuse users, in my opinion its fine as it is rn.

**Comment by IceDBorn** [comment]
@Bnyro Some of us use libretube for videos and music too, it would be annoying having to long press any song you want to play.

**Comment by IceDBorn** [comment]
@Bnyro You can add an "Audio only" switch in the settings for this too. The official piped instance, uses this option to default all videos to audio only streaming mode. With this approach, all uses would be satisfied! Users who do not want all videos to run into background mode can use the app regularly by long pressing videos and users who want audio only mode to be persistent can use the settings toggle.

**Comment by IceDBorn** [comment]
@Relwi Yeah, I'm talking about future PRs, do not worry, you're doing great.

**Comment by Relwi** [comment]
I am not proud of the work on the subject of notification, but for now I'm done with this. Of course, in the future, I will create a new PRs with improvements.

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
Thank you for your efforts :)

**Pull request merged**
