### PR TITLE
Better compability on Android 11 in full screen

### PR DESCRIPTION
**Pull request by demirdegerli**
Implemented libs with compat ones. Also I don't know Kotlin so there might be bugs or type errors. Please edit the code if you find a mistake.

### CODE REVIEW

**Comment by Bnyro** [comment]
As the PR adds the use of a compat, we should probably get rid of the if condition and the deprecated method below.
Did you test whether it fixes the issue?

**Comment by demirdegerli** [comment]
I tested in a blank Kotlin project, built it and it worked. Because of I couldn't build LibreTube.

**Comment by demirdegerli** [comment]
Also I didn't remove the non-compat ones in case of something breaks.

**Comment by Bnyro** [comment]
The CI is broken too so no wonder it's not building for you. Apart from that I wonder how using the compat should have changed something here really because according to what I found the methods called would be still the same as before the change on Android 9 and up

**Comment by demirdegerli** [comment]
First tap shows the system UI, second tap shows the OSD. It's like there is something between the front and LibreTube UI. An invisible divider dissolves at first tap.
https://user-images.githubusercontent.com/67432156/212762346-d448fbfb-44b2-4330-885d-2694beeba41b.mp4

**Comment by Bnyro** [comment]
I've been writing a more elegant solution now (#2727) which should do what you initially intended to, feel free to test the debug builds!

**Pull request closed without merging**
