### PR TITLE
Gradle cleanup

### PR DESCRIPTION
**Pull request by imashnake0**
Just made some minor changes to the build files.

**Summary of changes:**
1. Moved [repositories to `settings.gradle`](https://developer.android.com/studio/releases/gradle-plugin#settings-gradle) and used [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) to apply plugins.
2. Added indents/white spaces to the app build file.

P.S. The app looks amazing!

### CODE REVIEW

**Comment by imashnake0** [comment]
I can implement [version catalogs](https://docs.gradle.org/current/userguide/platforms.html) if that's something you guys are interested in having.

**Comment by Bnyro** [comment]
Hmm, why does CodeQL fail :/

**Comment by archroid** [comment]
Can you fix the codeQL's error? We would appreciate it <3

**Comment by imashnake0** [comment]
Sorry for not getting back sooner. I'm not entirely sure why the Code QL thing is failing tbh. Please let me know if there is something apparently wrong with my changes.

**Comment by imashnake0** [comment]
[Version catalogs](https://docs.gradle.org/current/userguide/platforms.html) are seemingly not as helpful as they are with Kotlin DSL, I can also migrate the build logic to Kotlin DSL if that's desirable, but I'll leave that decision to you guys. I did push some draft changes tho :wink:.

**Comment by archroid** [comment]
image
You understand the problem or not? I don't get it.

**Comment by imashnake0** [comment]
> image You understand the problem or not? I don't get it.

I did go through the logs and [tried to troubleshoot](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#automatic-build-for-a-compiled-language-fails) but couldn't make much of the docs since I'm not super familiar with CodeQL. I fail to see how it has anything to do with my changes from the logs so if you could guide me that'd be great.

**Comment by archroid** [comment]
As I searched It looks like gradle's fault. Some changes are not applied to the github build script after the gradle update but I'm not sure. 
Can you guys find the problem? @Bnyro  @FireMasterK

**Comment by imashnake0** [comment]
Note that we might need to add `enableFeaturePreview("VERSION_CATALOGS")` if we're downgrading Gradle.

**Comment by archroid** [comment]
> Note that we might need to add `enableFeaturePreview("VERSION_CATALOGS")` if we're downgrading Gradle.

I just want to check where the problem is

**Comment by archroid** [comment]
Ok the problem was that DSL thing of the new gradle. I merge this PR and you make another one specifically for DSL and wait for CodeQL to support it. And also congrats of being a contributor. :D

**Comment by imashnake0** [comment]
> [Version catalogs](https://docs.gradle.org/current/userguide/platforms.html) are seemingly not as helpful as they are with Kotlin DSL, I can also migrate the build logic to Kotlin DSL if that's desirable, but I'll leave that decision to you guys. I did push some draft changes tho wink.

As a follow-up, please let me know of your decision and I can create a PR with the build logic migration and some more changes related to version catalogs. I was hoping to merge this only after those changes (which is why I marked it as a draft) but seeing as this is merged, I'm okay with creating a new PR to address the pending changes.

**Comment by archroid** [comment]
If you find these changes really helpful, you can do it. @Bnyro What's your idea?

**Comment by Bnyro** [comment]
I don't have an idea xD
If there are any benefits we would appreciate if you add it :)

**Comment by imashnake0** [comment]
> I don't have an idea xD If there are any benefits we would appreciate if you add it :)

Got it, I'll create another PR over the weekend.

**Pull request merged**
