### PR TITLE
refactor: Rewrite comments fragments using Paging library

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Improve the comment and comment replies fragments by using the paging library.

### CODE REVIEW

**Comment by Bnyro** [comment]
I noticed 3 small regressions:
1. The "back" button on the top left is no longer visible when visiting the comment replies fragment, as it's been before the changes.
2. There's no loading indicator when opening the replies of a comment / it's positioned at the bottom sometimes instead of the top.
3. The channel avatars of the commentors/repliers are having the same issue as in https://github.com/libre-tube/LibreTube/pull/5528#discussion_r1463283480.

**Review by Bnyro — COMMENTED** [review]
I noticed 3 small regressions:
1. The "back" button on the top left is no longer visible when visiting the comment replies fragment, as it's been before the changes.
2. There's no loading indicator when opening the replies of a comment / it's positioned at the bottom sometimes instead of the top.
3. The channel avatars of the commentors/repliers are having the same issue as in https://github.com/libre-tube/LibreTube/pull/5528#discussion_r1463283480.

**Review by Bnyro — COMMENTED** [review]
The comment fragment works very well now, thank you for looking into my comments!

I noticed one small visual issue when opening the replies fragment when the comment has a lot of issues - it seems like the main comment is duplicated - once at the bottom of the replies and once at the top. When scrolling up again, the duplicated comment at the bottom vanishes. It looks like the layout isn't properly re-created here when the comments are loaded?

I'm not really familiar with the paging library, so I can't really tell what's going on.

**Comment by Isira-Seneviratne** [comment]
> The comment fragment works very well now, thank you for looking into my comments!
> 
> I noticed one small visual issue when opening the replies fragment when the comment has a lot of issues - it seems like the main comment is duplicated - once at the bottom of the replies and once at the top. When scrolling up again, the duplicated comment at the bottom vanishes. It looks like the layout isn't properly re-created here when the comments are loaded?
> 
> I'm not really familiar with the paging library, so I can't really tell what's going on.

That's because the parent comment is first displayed before the replies are loaded into the adapter.

[This guide](https://developer.android.com/topic/libraries/architecture/paging/v3-overview) should help with understanding the paging library.

**Review by Bnyro — APPROVED** [review]

**Comment by Pamilg8** [comment]
> The comment fragment works very well now, thank you for looking into my comments!
> 
> I noticed one small visual issue when opening the replies fragment when the comment has a lot of issues - it seems like the main comment is duplicated - once at the bottom of the replies and once at the top. When scrolling up again, the duplicated comment at the bottom vanishes. It looks like the layout isn't properly re-created here when the comments are loaded?
> 
> I'm not really familiar with the paging library, so I can't really tell what's going on.

In single-answer comments, you must go back and reload the answer to see the answer. Do you have a solution?

**Comment by Isira-Seneviratne** [comment]
> In single-answer comments, you must go back and reload the answer to see the answer. Do you have a solution?

Changing `position - 1` to `position` in the comment adapter might fix the issue (I'm not able to test it at the moment).

**Pull request merged**
