### PR TITLE
Improve latvian translation

### PR DESCRIPTION
**Pull request by janisslsm**
Improved latvian translations, fixed some grammatical errors and a few other things.

### CODE REVIEW

**Comment by Bnyro** [comment]
Please update the translations via Weblate and not as a PR

**Comment by janisslsm** [comment]
> Please update the translations via Weblate and not as a PR next time

Sorry my bad, should I keep this PR open?

**Comment by janisslsm** [comment]
I moved the translations over to weblate, I'll close this PR.

**Comment by Bnyro** [comment]
> I moved the translations over to weblate, I'll close this PR.

Thank you

**Pull request closed without merging**
