### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [LibreTube/LibreTube](https://hosted.weblate.org/projects/libretube/libretube/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Bnyro** [comment]
@archroid just merging 18 changed strings lol

**Comment by archroid** [comment]
lol Nothing else to do.

**Comment by Bnyro** [comment]
@archroid maybe fix a few bugs? lol

**Comment by archroid** [comment]
Trying to solve CodeQL error @Bnyro

**Pull request merged**
