### PR TITLE
chore(roadmap): add direct use of NPE, YTjs as not planned

### PR DESCRIPTION
**Pull request by Pamilg8**
Let them know that you don't plan to do this yet so that no more duplicate issues are opened.

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]
Thanks!

**Comment by IndusAryan** [comment]
@akano12 any eta on innertube or newpipe extractor, i am seeing it in a roadmap?

**Comment by Pamilg8** [comment]
> @akano12 any eta on innertube or newpipe extractor, i am seeing it in a roadmap?

Added as not planned

**Pull request merged**
