### PR TITLE
feat: landscape layout for player page

### LINKED ISSUE #3198: Landscape layout for player page
### Describe your suggested feature

Hi, I want to use this app on landscape mode.

Settings page support the landscape mode.

Main page support the landscape mode.

Full-screen player page support the landscape mode.

But description page not support the landscape mode.

Please enable landscape mode on description page.

Screenshot_2023-02-27-01-28-28-854_com github libretube

Thanks.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #3198

### CODE REVIEW

**Comment by rozari0** [comment]
When I open Settings it open in portrait mode first and then rotate to landscape mode.
Otherwise works fine. 

Tested on Android 9.

**Comment by Bnyro** [comment]
Hmm, do you have related streams disabled?

**Comment by Bnyro** [comment]
Oh, I can reproduce the issue now. Seems like this was introduced a few commits ago, it did work pretty well when I merged this PR.

Please open an issue so that we don't forget to fix this before the next release.

**Comment by Baardi** [comment]
Opened https://github.com/libre-tube/LibreTube/issues/5131

**Pull request merged**
