### PR TITLE
File permission on Pie or below

### PR DESCRIPTION
**Pull request by Roguo-Kato**

### CODE REVIEW

**Comment by Roguo-Kato** [comment]
Sorry, I made a mistake in using github.

> In fact I wanted to avoid requiring any storage permissions, are you aware of any directory that the app can access without permissions below Android Pie?

> Then we could just use that directory for those Android versions instead of requiring storage permissions.

I think if it use the file picker and DocumentFile, it will haven't request WRITE_EXTERNAL_STORAGE. But DownloadManager requires WRITE_EXTERNAL_STORAGE.

**Comment by Bnyro** [comment]
Independent of that, please only create one PR and not two separated ones for the same thing.
Apart from that I still don't really want to add storage permissions to the app and would prefer finding a different solution for the issue.

**Comment by Roguo-Kato** [comment]
Thank you for your advice. I use Android 12 and 5.0, and there are some other suggestions, but is it annoying to make PR each time?

**Comment by Bnyro** [comment]
Your two PRs do are targeting the same issue so one would be preferred, apart from it such a change should have discussed in a bug report first.

**Comment by Roguo-Kato** [comment]
I realized that I was making patch1 and patch2. I repaired.
>it such a change should have discussed in a bug report first.
I had watched it, but the discussion were closed without fixing.
(https://github.com/libre-tube/LibreTube/issues/2059)
I had understood that DownloadManager.enqueue was the cause, so I just wanted to make a suggestion for a dream-like app.

**Pull request closed without merging**
