### PR TITLE
Update baseline profile configuration

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Updated the generated baseline and startup profiles with the latest changes.
* Updated the baseline profile generation configuration.

### CODE REVIEW

**Comment by Bnyro** [comment]
> Updated the generated baseline and startup profiles with the latest changes.
>
We need to do this after each change now? Wouldn't it be better to just do it once before the release?

**Comment by Isira-Seneviratne** [comment]
> > Updated the generated baseline and startup profiles with the latest changes.
> >
> We need to do this after each change now? Wouldn't it be better to just do it once before the release?

You're right. I'll just include the config change and remove the rest.

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
@Isira-Seneviratne I've been trying to update the baseline profile, but I can't seem to get it work (tried with Android Studio and `./gradlew generateBaselineProfile`). What's the right command/way to generate these?

**Comment by Isira-Seneviratne** [comment]
Yeah, there seems to be an issue when including the native libraries. To generate the profile, I commented out some lines in app/build.gradle (I've added a comment indicating as such).

**Comment by Bnyro** [comment]
Hmm, it still gives me some errors when trying to generate the profile :/

Could you please create them and make a PR when you have time (no need to hurry, just when you're free :) )?

**Comment by Isira-Seneviratne** [comment]
Sure.

**Pull request merged**
