### PR TITLE
UI improvements for search and player fragment

### PR DESCRIPTION
**Pull request by archroid**

### CODE REVIEW

**Comment by archroid** [comment]
image
image

**Comment by lilcheti** [comment]
would you resolve the conflicts

**Comment by archroid** [comment]
> would you resolve the conflicts

Can't you do it yourself? I'm busy a bit.

**Review by its0x08 — APPROVED** [review]

**Comment by archroid** [comment]
I will make all changes again on the latest code. But this time please accept it :))

**Pull request closed without merging**
