### PR TITLE
Update dependencies, improvements, TimeAgo changes, and StreamItem duration

### LINKED ISSUE #29: Show video time duration
something like this -

### PR DESCRIPTION
**Pull request by FireMasterK**
Closes #29

### CODE REVIEW

**Comment by rimthekid** [comment]
Look at #27 should we change it to look like that?

**Comment by FireMasterK** [comment]
That can be done too (in a different pr), the screenshot is to showcase the video duration on the thumbnails.

**Comment by dhishkyaon** [comment]
can you change the transparency to zero?
Video duration will be more visible then.

**Comment by FireMasterK** [comment]
> can you change the transparency to zero?
> Video duration will be more visible then.

The color was taken from NewPipe, I think it's good enough for now.

**Pull request merged**
