### PR TITLE
feat: support close video on MiniPlayer swipe down

### LINKED ISSUE #2020: Swipe down to close miniplayer
### Describe your suggested feature

When the video player is minimised on the app, one can close the video by further swiping down the player just like YouTube and NewPipe.

Screenshot_20221124-114602~2

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by RafaelsRamos**
Adds support for closing the video being played when the user downswipes the MiniPlayer.

https://github.com/libre-tube/LibreTube/assets/40279132/4d0a4a0a-ab84-4ec3-9c19-c51852dedd41

closes #2020

### CODE REVIEW

**Comment by Pamilg8** [comment]
Wouldn't it be nice to add this option as on/off in Settings?

**Comment by NeeRaj-2401** [comment]
> Thank you👍 Wouldn't it be nice to add this option as on/off in Settings?

Bruhh 💀, there is already plenty of settings that are customisable, this small behaviour isn't worth to add one

**Comment by akano12** [comment]
> > Thank you👍 Wouldn't it be nice to add this option as on/off in Settings?
> 
> Bruhh 💀, there is already plenty of settings that are customisable, this small behaviour isn't worth to add one 

Nah let's add a new one, there aren't enough options/settings to choose from.


And jokes aside, if you don't want to use then don't swipe down tk close the mini player maybe 🙄🙄🙄🙄

**Comment by IndusAryan** [comment]
> Thank you👍 Wouldn't it be nice to add this option as on/off in Settings?

yes, i think it needs a preference , but i hate miniplayer i think there should be a setting to direclty close video when it is gestured down to miniplayer. would be awesome to have it.

**Comment by Pamilg8** [comment]
> > Thank you👍 Wouldn't it be nice to add this option as on/off in Settings?
> 
> yes, i think it needs a preference , but i hate miniplayer i think there should be a setting to direclty close video when it is gestured down to miniplayer. would be awesome to have it.

Why the 👎emoji?

**Comment by RafaelsRamos** [comment]
My 2 cents, I agree with NeeRaj-2401 and akano12, in the sense that this is such a small behaviour, it might not be worth adding one more setting to enable/disable it.
That being said, if we deem it the best approach, I am willing to add it 👍

**Comment by IndusAryan** [comment]
> My 2 cents, I agree with NeeRaj-2401 and akano12, in the sense that this is such a small behaviour, it might not be worth adding one more setting to enable/disable it.
> That being said, if we deem it the best approach, I am willing to add it 👍 

my 10 cents, i think this should be a setting , just like many ultra useful settings like different qualities for fullscreen and normal screen i think i also need another quality setting for miniplayer, i hope devs add it, maybe i should add it or open issue.

**Comment by RafaelsRamos** [comment]
What do you think Bnyro, should we go ahead with the setting? If so, maybe should be done in another PR?

**Comment by akano12** [comment]
> What do you think Bnyro, should we go ahead with the setting? If so, maybe should be done in another PR?

Pretty sure the reply above yours is satire (quality option for mini player...)

**Comment by RafaelsRamos** [comment]
IndusAryan always looks serious to me 🥹

**Review by Bnyro — APPROVED** [review]
Works very well, thank you!

**Pull request merged**
