### PR TITLE
Add Instance adminForge.de

### PR DESCRIPTION
**Pull request by Dominion0815**

### CODE REVIEW

**Comment by FireMasterK** [comment]
Any reason why you're not adding your instance to the list Piped maintains? Libretube uses it, via https://piped-instances.kavin.rocks/

If you'd like me to add it there, let me know!

**Comment by Dominion0815** [comment]
Oh how it's possible?

**Comment by Bnyro** [comment]
Kavin is right, we don't use the array-list you changed for instances anymore.

Best way is to either open an issue on [the Piped repo](https://github.com/teampiped/piped) providing some info about the instance (region, CDN,...) or just provide the info here and make it up with Kavin :)

**Comment by Bnyro** [comment]
Looks like Kavin already added it haha :p

**Pull request closed without merging**
