### PR TITLE
feat: Support for feed pagination

### LINKED ISSUE #3693: Implement support for the new upcoming feed pagination in API
### Describe your suggested feature

See https://github.com/TeamPiped/Piped/pull/2353

We need to take the last video's `uploaded` timestamp and use that as the `start` query parameter.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #3693

#### The changes have not been tested yet as there's no instance already supporting feed pagination. However, they should be tested before creating a new release.

### CODE REVIEW

**Comment by FireMasterK** [comment]
> The changes have not been tested yet as there's no instance already supporting feed pagination. However, they should be tested before creating a new release.

I should really create a new 'alpha' or something similar instance for testing changes :thinking:

**Comment by Bnyro** [comment]
That would be ideal, yes.

**Comment by Isira-Seneviratne** [comment]
The AndroidX Paging library might be useful: https://developer.android.com/jetpack/androidx/releases/paging

**Comment by Bnyro** [comment]
True, that could likely be used at other places too such as the search adapter or the playlist videos adapter.

**Pull request closed without merging**
