### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes issue #5141.
I took the approach to switch to audio player.

### CODE REVIEW

**Comment by Bnyro** [comment]
This also means that the normal player is no longer in sync, which should be discussed first or made optional.

**Comment by Pamilg8** [comment]
Lately the audio player is not working in the background

**Comment by M00NJ** [comment]
Sounds like a pretty good idea imo. Though I think if it switches automatically to adio mode when the screen is turned off, it should also automatically switch back to video, when the device gets unlocked.

**Comment by Pamilg8** [comment]
Also, we click the home button and use other applications. It would be great if the audio player starts when you tap the home button. For continuous playback in the background, we need to press the audio + home buttons, then return to the application and press the button again to open the video player. Considering that this is difficult, it is better if we correct it.

**Comment by IndusAryan** [comment]
> Note: An option similar to opening a popup when you click the home button.

another option??, you are right in first like , whenever app is in background wheter screen off or on, it should switch to audio, but it'll be annoying if playback stops for sometime while changing the state or you already got the fix @arkibax ?

**Comment by Pamilg8** [comment]
I just expressed my opinion. The issue is tagged as a discussion

> > Note: An option similar to opening a popup when you click the home button.
> 
> another option??, you are right in first like , whenever app is in background whether screen off or on, it should switch to audio, but it'll be annoying if playback stops for sometime while changing the state or you already got the fix @arkibax ?

**Comment by IndusAryan** [comment]
> I just expressed my opinion. The issue is tagged as a discussion

lol, do i really sound that bad, i just asked if you want another option??, idc if it gets another option

**Comment by akano12** [comment]
We need an option called "Thanos" that when toggled would randomly delete half of the options available in the settings

**Comment by IndusAryan** [comment]
> We need an option called "Thanos mode" that when toggled would randomly delete half of the options available in the settings

i can add that if bnyro is serious about it.

second: i am also looking to remove many settings, but i dont know which setting to remove . team libretube should make a list of them in discussion.

**Comment by Pamilg8** [comment]
> > We need an option called "Thanos mode" that when toggled would randomly delete half of the options available in the settings
> 
> i can add that if bnyro is serious about it.
> 
> second: i am also looking to remove many settings, but i dont know which setting to remove . team libretube should make a list of them in discussion.

Why are you deleting? I didn't understand

**Comment by FireMasterK** [comment]
I think the best behaviour would be to have it switch to the background player when the screen it turned off, and switch back to the video player, seeking to the background player's position when the device is unlocked.

**Comment by Pamilg8** [comment]
> I think the best behaviour would be to have it switch to the background player when the screen it turned off, and switch back to the video player, seeking to the background player's position when the device is unlocked.

Yes, he did

**Comment by 0xrxL** [comment]
From what I understood, this PR is stalled, due to some issue encountered by some users, including the lack of sync between audio and video (and viceversa) players during foreground/background switching.

I'm a dev...but not an Android dev (so I don't know how everything exactly works), but can't be eventually possible to run two player instances (video and audio together) and mute one of them depending by the app focus (foreground or background), to keep the sync and bypass every eventual bug caused by the solution in this PR?

**Comment by IndusAryan** [comment]
> From what I understood, this PR is stalled, due to some issue encountered by some users, including the lack of sync between audio and video (and viceversa) players during foreground/background switching.
> 
> I'm a dev...but not an Android dev (so I don't know how everything exactly works), but can't be eventually possible to run two player instances (video and audio together) and mute one of them depending by the app focus (foreground or background), to keep the sync and bypass every eventual bug caused by the solution in this PR?

together one will work, but it will require some higher memory as well as cause increased data usage, and syncing problem wont get solved there too, suppose the video loads but the audio track doesnt, and it will also increase some load on piped

**Comment by 0xrxL** [comment]
> > From what I understood, this PR is stalled, due to some issue encountered by some users, including the lack of sync between audio and video (and viceversa) players during foreground/background switching.
> > I'm a dev...but not an Android dev (so I don't know how everything exactly works), but can't be eventually possible to run two player instances (video and audio together) and mute one of them depending by the app focus (foreground or background), to keep the sync and bypass every eventual bug caused by the solution in this PR?
> 
> together one will work, but it will require some higher memory as well as cause increased data usage, and syncing problem wont get solved there too, suppose the video loads but the audio track doesnt, and it will also increase some load on piped

Not necessarily...

For example: video player could split audio and video tracks, and use its instance to buffer both for itself and audio player too.

Assuming that all this can be done, of course...

**Pull request closed without merging**
