### PR TITLE
Update MainActivity.kt

### PR DESCRIPTION
**Pull request by NR8124**
Just wanted the sponsors section and its notification to be enabled by default in which ONLY sponsor category has to be enabled by dafault.. others can be enabled manually.
but this change was necessary because the api itself is made for this intension

### CODE REVIEW

**Comment by Bnyro** [comment]
That's a good idea but we'll have to change some other code for it too :)

**Comment by Bnyro** [comment]
You'll have to add 'defaultValue="true"' to all the categories you want to enable in app/src/main/res/xml/sponsorblock_settings.xml

**Comment by NR8124** [comment]
ok let me just check it once

**Comment by Bnyro** [comment]
The lines you changed shouldn't really have a big impact :)

**Comment by Bnyro** [comment]
Feel free to ask me if you have questions :)

**Comment by NR8124** [comment]
i made some changes there.. please check it out

**Comment by Bnyro** [comment]
looks good :)
I think we could also enable sponsorblock itself and its notifications by default (if you want to do so)

**Comment by NR8124** [comment]
yes i want to do that 
basically
1. sponsorblock
2. its notifications
3. sponsors category
i want  these three toggles to be enabled by default

**Comment by Bnyro** [comment]
Oh, you enabled that already, I'm just brain afk :p

**Comment by NR8124** [comment]
oh thankss!! 
so will you be pulling this changes ?

**Comment by Bnyro** [comment]
sure :)

**Comment by NR8124** [comment]
thanks for the help budyy !!

**Comment by Bnyro** [comment]
no problem, feel free to join us on Element (preferred) or Telegram (links are in the Readme). Communication is easier there :)

**Comment by NR8124** [comment]
yeah, i have already joined Libretube and  Libretube Alpha over  telegram...

**Comment by Bnyro** [comment]
these are only announcement channels, for discussions you should join t.me/libretubechat

**Comment by NR8124** [comment]
sure :)

**Pull request merged**
