### PR TITLE
Search Filters, Nextpage in Search, Search History Settings

### PR DESCRIPTION
**Pull request by Bnyro**

### CODE REVIEW

**Comment by Bnyro** [comment]
Don't merge, I fucked up with the API
@FireMasterK Please update your docs lol

**Comment by Bnyro** [comment]
Should work now

**Comment by IceDBorn** [comment]
What about youtube music specific filters?

**Comment by Bnyro** [comment]
> What about youtube music specific filters?

@FireMasterK Are they supported by the API?

**Comment by Bnyro** [comment]
> @Bnyro I think that they are supported, they are being used by the official instance.

Yes, they are, but I have to wait for Kavin to tell me the queries since the docs don't provide any information about jt :)

**Comment by IceDBorn** [comment]
@Bnyro No worries, both of you are fantastic!

**Pull request merged**
