### PR TITLE
Use bundleOf().

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Use the [`bundleOf()`](https://developer.android.com/reference/kotlin/androidx/core/os/package-summary#bundleOf(kotlin.Array)) Kotlin helper method.

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
Hey @Isira-Seneviratne,
are you reachable somewhere on Matrix or is there any other good way to get in touch with you?
Your GitHub profile doesn't mention anything, so I assume you may not want to use anything else than GitHub for communication (which would be fine too though).
Cheers

**Comment by Isira-Seneviratne** [comment]
> Hey @Isira-Seneviratne,
> are you reachable somewhere on Matrix or is there any other good way to get in touch with you?

Yeah, I'm on Matrix via the Element app.

> Your GitHub profile doesn't mention anything, so I assume you may not want to use anything else than GitHub for communication (which would be fine too though).

I forgot to include that on my profile, thanks for reminding. I'll update my profile.

**Comment by Isira-Seneviratne** [comment]
> Hey @Isira-Seneviratne,
> are you reachable somewhere on Matrix or is there any other good way to get in touch with you?

Yeah, I'm on Matrix via the Element app.

> Your GitHub profile doesn't mention anything, so I assume you may not want to use anything else than GitHub for communication (which would be fine too though).

I forgot to include that on my profile, thanks for reminding. I'll update my profile.

**Comment by Bnyro** [comment]
Alright, awesome!
Feel free to join https://matrix.to/#/#LibreTube:matrix.org or otherwise, if you prefer not to, I'm available under @bnyro:matrix.org :)

**Pull request merged**
