### PR TITLE
Cronet

### PR DESCRIPTION
**Pull request by janisslsm**
I've attempted to implement cronet, I'm not sure if it makes any difference so I'd like some feedback to see if anyone notices a difference in speed.
A debug build should be available in checks from the CI

### CODE REVIEW

**Comment by FireMasterK** [comment]
I really don't like this approach of implementing cronet by copying it's source code, I would wait for them to release a maven dependency: https://github.com/google/cronet-transport-for-okhttp/issues/1

**Comment by janisslsm** [comment]
> I really don't like this approach of implementing cronet by copying it's source code, I would wait for them to release a maven dependency: [google/cronet-transport-for-okhttp#1](https://github.com/google/cronet-transport-for-okhttp/issues/1)

Yeah, I'm aware of it. I'm just experimenting to see if cronet makes a difference

**Comment by ag2s20150909** [comment]
exoplayer has cronet extensions

https://github.com/google/ExoPlayer/tree/release-v2/extensions/cronet

**Comment by FireMasterK** [comment]
> exoplayer has cronet extensions
> 
> https://github.com/google/ExoPlayer/tree/release-v2/extensions/cronet

That's already being used since https://github.com/libre-tube/LibreTube/pull/130

**Pull request closed without merging**
