### PR TITLE
Fix notification freezing issue

### LINKED ISSUE #1601: Notification sometimes gets freezed
### Steps to reproduce
I was watching a video and then, i exited from the app for sometime and when i returned back, the video i was playing was gone but the notification was still there and no response then.

But when i start playing the same video, then it back to normal and working fine.

Check this out:
https://drive.google.com/file/d/18H2kwUWbSJctASu50sjfUz3xLnKnrbnO/view

### Expected behavior

nil

### Actual behavior

nil

### LibreTube version

0.6.1

### Android version

Android 10

### Other details

Offtopic: sorry to share via drive as everytime i upload video, it says "low memory". I hope you understand:⁠-⁠)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1722: libretube video notification doesn't go away.
### Steps to reproduce

No sure how to reproduce. I was just playing video and now it doesn't go away. Happend before, not rarely.

### Expected behavior

Should close video and notification.

### Actual behavior

Here is an example https://piped.kavin.rocks/shorts/O-eXvX27JaM

### LibreTube version

0.7.0

### Android version

Android 9

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Kruna1Pate1**
The foreground service was still running when using the audio mode and then switching back to video (by pressing play button, play another video, or close app). 
So check when the video `isPlaying` and If `BackgroundMode` service is running first stop it and start video play.

However, i am not able to check what happens when OS kills this foreground service. But, since the notification is cleared in `onDestroy` of `BackgroundMode` service it should work fine. Please give it try.

One more little fix, when `activity` is in PiP then it gives orientation as landscape always, which leads to `setFullscreen` and `BrightnessHelper` thinks it's full-screen :)

(Hope) Closes #1601, closes #1722

### CODE REVIEW

**Comment by Bnyro** [comment]
Thanks for the PR!
However, we still have the issue that the notification is getting stuck when using the `background mode` and trying to remove the video manually as the foreground service is still running since the media session is still active, what's the issue with #1722. So I don't really think that the PR can solve that specific issue (altough it does fix others for sure). I've also tested it and it's still the case for the background mode (which isn't a wonder as you didn't touch the lonely background mode). So it might partially fix the issue but only for the case when using it in combination with the normal player I think.

**Comment by Kruna1Pate1** [comment]
That seems issue,
So, behavior should be like 
When `Background mode` is used it should stop in the following conditions:
- [x] When a new video is played
- [x] When the video is resumed (using play button on the player)
- [ ] When the video is closed (using the cross symbol)
- [ ] When user manually removes the application from task manager (or recent apps)

But, should continue playing when:
- [x] User navigate away from app without closing video
- [x] OS decides to kill app

Let me know if I am missing something.

**Comment by Kruna1Pate1** [comment]
> notification is getting stuck when using the `background mode`

Is notification not responding (i.e. play pause buttons) ?

**Comment by Bnyro** [comment]
> > notification is getting stuck when using the `background mode`
> 
> Is notification not responding (i.e. play pause buttons) ?
>
No, the notification stays responsive.

**Comment by Kruna1Pate1** [comment]
I think 93546382b9de6fa30ed7337a0eeb070695aa6199 should solve this.

**Comment by Bnyro** [comment]
That looks like a good solution to me, thank you! <3

**Pull request merged**
