### PR TITLE
Add support for seek to timestamp in comments

### LINKED ISSUE #1383: Comment timestamps
### Describe your suggested feature

It would be nice if comments that mention timestamps could be a link that would jump the player to that time in the video.

### Other details

 It's useful in long videos where people will put unofficial chapter markers in the comments, e.g.

[1:20](#) - X happens
[10:50](#)  - Y happens
[1:02:06](#) - Z happens

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Kruna1Pate1**
Working with most of the time stamps.
Closes #1383

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]
Code-wise looks good to me!

**Comment by Kruna1Pate1** [comment]
i think regex is correct. I forgot `minutes` and `seconds` are till `59` which is checked in regex :/

**Comment by Kruna1Pate1** [comment]
looks fine now

**Comment by FireMasterK** [comment]
I want to add that HTML-based comments are coming to the API soon, so this shouldn't be the long-term solution used!

**Comment by Kruna1Pate1** [comment]
So, should we merge it or wait for the update?

**Comment by FireMasterK** [comment]
I would recommend waiting since that would have a lot more breaking changes too I think. (since links would also be clickable, and text can be bold/italic/strikethrough)

**Comment by FireMasterK** [comment]
The PR for this is ready at https://github.com/TeamPiped/Piped-Backend/pull/481, waiting for LibreTube and Yattee to be ready before I merge it :)

**Comment by Kruna1Pate1** [comment]
I think it will be easy fix just like we are handling [description](https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt#L924) or even less if only in HTML and no plain/MD text.

**Pull request closed without merging**
