### PR TITLE
Comment replies

### LINKED ISSUE #303: Comments on comments?
### Describe your suggested feature

The original [Piped](https://github.com/TeamPiped/Piped) and [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) has supported this feature.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #303

### CODE REVIEW

**Comment by enessgokalp** [comment]
When click to any comment app closing

**Comment by Bnyro** [comment]
@enessgokalp Could you send me the debug log?

**Comment by enessgokalp** [comment]
How can i send

**Comment by Bnyro** [comment]
@enessgokalp I think I fixed it now, could you please try the latest CI build?

**Comment by Bnyro** [comment]
You're welcome :)

**Pull request merged**
