### PR TITLE
fix: Incorrect actions management through bluetooth devices

### LINKED ISSUE #5422: Cannot continue playback via Bluetooth
### Steps to reproduce

1. Open app.
2. Start play any video
3. Click stop
4. Click play on Bluetooth headphone. (not work)

### Expected behavior

When you press the headset's Bluetooth button, playback should continue

### Actual behavior

Once stopped, it is impossible to resume via Bluetooth

### LibreTube version

0.21.0

### Android version

13

### Other details

This error appears in different playback modes.
In video playback, audio-only playback, and background playback.
It is very rare that everything works correctly.
Other programs work correctly, so I believe this error is local to LibreTube.
It has been around for a long time, not just the latest version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by RafaelsRamos**
Ensure the player pauses and plays correctly through the action of input devices.

closes #5422

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]
These small "typos" are really hard to spot, thank you!

**Comment by Bnyro** [comment]
Why is @FineFindus shown to be the person that did this commit btw?

**Comment by RafaelsRamos** [comment]
Great question! I don't know the answer 🤔

**Comment by FineFindus** [comment]
The only reason I know of is that either a commit I made was rebased and edited, or the git user was changed to mimic me, since I'm pretty sure I never wrote that line.

**Comment by RafaelsRamos** [comment]
I did have to travel through the git history a lot to understand the issue, so maybe I messed up something along the way :|

**Pull request merged**
