### PR TITLE
Migration to Media3

### LINKED ISSUE #3600: Low quality thumbnail in Android 13 background play notification
### Steps to reproduce

Play a video and look at the notifaction for controling background play

### Expected behavior

Thumbnail should be high resolution

### Actual behavior

Thumbnail has a very low resolution

### LibreTube version

0.14.0

### Android version

Android 13

### Other details

Screenshot of what I mean: 
Screenshot_20230421-123412_LibreTube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
Regressions (already fixed):
- [x] Video metadata on lockscreen 
- [x] Player notification actions
- [x] Skip forward player notification action not visible

see https://android-developers.googleblog.com/2023/03/media3-is-ready-to-play.html

closes #3600

### CODE REVIEW

**Comment by Bnyro** [comment]
Would be awesome if we could get some testers on this, also on different Android versions if possible since this change could be breaking some things.

**Comment by rozari0** [comment]
> Would be awesome if we could get some testers on this, also on different Android versions if possible since this change could be breaking some things.

Can you create a testing branch and merge this there?

**Comment by FireMasterK** [comment]
> Can you create a testing branch and merge this there? 

How would that help? You could just take the latest build from this branch

**Review by Isira-Seneviratne — APPROVED** [review]
I tested out the change, and there don't seem to be any issues (I played a couple of videos).

**Comment by rozari0** [comment]
> How would that help? You could just take the latest build from this branch

I was unable to install from this build, Ig that has something to do with signing. (I tried on insular, so it doesn't conflict with main alpha build.)

**Comment by Bnyro** [comment]
If nobody comes up with an issue within the next day, I'll just merge this.

**Review by FireMasterK — APPROVED** [review]
Works fine from my testing!

**Pull request merged**
