### PR TITLE
Add Sponsorblock highlight

### LINKED ISSUE #4059: Add highlight from Sponsorblock
### Describe your suggested feature

Currently, LibreTube previews chapters:

20230620_132553_temp

It would be cool if the highlight from Sponsorblock would also be shown there.

### Other details

If it's no problem, I'd be more than happy to implement this myself - this would help me learn Kotlin better and add a new awesome feature :D

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Myzel394**
Closes #4059 

This is how far I've come. This PR is not ready yet. Unfortunately, I can't find out how to extract the preview image and the app crashes when calling the `setCurrentChapterName`. I removed it for testing purposes now, but we need to find out why it's not working. Otherwise, loading the highlight, showing it in the chapters, automatically jumping to it, and changing it in the settings works fine.

This is the error:

```
java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'DefaultDispatcher-worker-2'
Expected thread: 'main'
See https://developer.android.com/guide/topics/media/issues/player-accessed-on-wrong-thread
	at androidx.media3.exoplayer.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2680)
	at androidx.media3.exoplayer.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:1069)
	at com.github.libretube.ui.fragments.PlayerFragment.getCurrentChapterIndex(PlayerFragment.kt:1251)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:1235)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$default(PlayerFragment.kt:1225)
	at com.github.libretube.ui.fragments.PlayerFragment.initializeChapters(PlayerFragment.kt:1221)
	at com.github.libretube.ui.fragments.PlayerFragment.access$initializeChapters(PlayerFragment.kt:127)
	at com.github.libretube.ui.fragments.PlayerFragment$fetchSponsorBlockSegments$1.invokeSuspend(PlayerFragment.kt:798)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2b2742, Dispatchers.IO]
```

### CODE REVIEW

**Comment by Bnyro** [comment]
When calling the `exoPlayer` or `player`, use `handler.post { player.do something() }`

**Comment by Myzel394** [comment]
Perfect! Now we only need to find out how to load the image :sweat_smile:

**Comment by Bnyro** [comment]
For the image, you basically need to use https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/listeners/SeekbarPreviewListener.kt#L93 with `streams.previewFrames` which will output you the URL of the image. Then you can just set that as the chapter URL, and it'll work :rocket:

**Comment by Bnyro** [comment]
So the best way is to move the method I linked above to the `PlayerHelper` object, to avoid code duplications, and use it for the seekbar and the SponsorBlock highlight.

**Comment by Myzel394** [comment]
@Bnyro The function you mentioned returns a `PreviewImage`, but `ChapterSegment` expects a String

**Review by Bnyro — APPROVED** [review]
Thanks!

**Pull request merged**
