### PR TITLE
fix: resolve stuttering when scrolling to the bottom of a video feed #4282

### PR DESCRIPTION
**Pull request by abGit9**
This pull request makes the following changes:

Fixes issue #4282
Resolves stuttering for ChannelFragment and PlaylistFragment. Could not fix SubscriptionsFragment because toggling function between Subscriptions and Channels did not work.  Will have to revisit.

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
Refactoring the ChannelFragment code to use the [paging library](https://developer.android.com/topic/libraries/architecture/paging/v3-overview) might be a better way of implementing this change.

**Comment by Pamilg8** [comment]
Stuttering occurs in the video, short, live, playlists sections of the channel, and videos in playlists.

**Comment by abGit9** [comment]
I'm not experiencing stuttering on my android phone , its android 14. Whats your version?

**Comment by abGit9** [comment]
I'm not experiencing stuttering in my phone, it is Android version 14.

**Comment by Pamilg8** [comment]
> I'm not experiencing stuttering in my phone, it is Android version 14.

Mine is android 12 and 13

**Comment by abGit9** [comment]
> Refactoring the code to use the [paging library](https://developer.android.com/topic/libraries/architecture/paging/v3-overview) might be a better way of implementing this change (I've already [done](https://github.com/libre-tube/LibreTube/pull/5528) some of the changes needed for the search results).

Using the paging library is a good idea. I agree with it. Though it will certainly optimize how data is managed and loaded for display, it does not deal with UI components directly. I do think that how the UI layout is structured currently(specifically in the fragment_channel.xml and fragment_playlist.xml  with nesting a recycler view in a scrollview) isn't good practice and is causing inefficiency when adding data items to the recyclerview. On my end the behavior has improved with the committed modifications.

Also, these modifications do not conflict with the Paging integrations that you have implemented. They deal more with altering the UI design with scrolling and not how data is retrieved, mangaged, and made available to the recycler view(Paging).

**Comment by Isira-Seneviratne** [comment]
I meant that altering the channel fragment to use the paging library would be a bit easier as the search adapter has been changed to extend `PagingDataAdapter` already.

**Comment by abGit9** [comment]
https://developer.android.com/reference/kotlin/android/widget/ScrollView
This doc states the following : " Never add a androidx.recyclerview.widget.RecyclerView or [ListView](https://developer.android.com/reference/kotlin/android/widget/ListView) to a scroll view. Doing so results in poor user interface performance and a poor user experience." 

This is currently the case in fragment_channel.xml and fragment_playlist.xml. This PR modifies it so scrollview is no longer used.

**Comment by Bnyro** [comment]
Please undo the formatting changes in app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt

**Comment by abGit9** [comment]
I reformatted the file as best I could. Let me know if there are any issues. Thank you.

**Comment by abGit9** [comment]
are there still formatting issues?

**Comment by Bnyro** [comment]
I'll look at it when I have time.

**Comment by Bnyro** [comment]
The PR does not compile at the moment, looks like something went wrong when you merged the latest changes into your branch. Also please do not use `git merge` , to avoid issues please use `git rebase`.

**Comment by abGit9** [comment]
yes, thank you. Will do.

**Pull request closed without merging**
