### PR TITLE
feat: allow dash without piped proxy

### PR DESCRIPTION
**Pull request by janisslsm**
This also allows you to watch newly released videos, HLS streams seem to be broken for newly released videos.

### CODE REVIEW

**Comment by Bnyro** [comment]
This should be applied at https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt#L377 too.

**Comment by Bnyro** [comment]
I don't really get why DASH works with `Local stream extraction` enabled, but doesn't if you use a working private Piped instance (no matter if `Disable Piped Proxy` is enabled or disabled) ...

**Comment by janisslsm** [comment]
> I don't really get why DASH works with `Local stream extraction` enabled, but doesn't if you use a working private Piped instance (no matter if `Disable Piped Proxy` is enabled or disabled) ...

Yeah, I'm not sure either and I haven't really looked into piped's backend enough to figure it out.

**Comment by Bnyro** [comment]
> Yeah, I'm not sure either and I haven't really looked into piped's backend enough to figure it out.
>
I've compared the YouTube stream URLs used for playback (with local stream extraction vs Piped instance) and both work fine when pasting the URL in the browser...

**Review by Bnyro — APPROVED** [review]

**Pull request merged**
