### PR TITLE
Refactor/cleanup code & layouts, introduce viewbinding

### PR DESCRIPTION
**Pull request by vassilisimon**
- Bump all dependencies, android gradle plugin, gradle wrapper & java version 
- A first take on refactor/cleanup/reformat code & layouts
- Introduce viewBinding to replace old `findViewById`
- Introduce `AppUtils` for common functions

### CODE REVIEW

**Comment by alefvanoon** [comment]
Thanks @vassilisimon , Are you still working on it?

**Comment by vassilisimon** [comment]
I'll finally it tomorrow.

**Comment by lilcheti** [comment]
I'm really looking forward to this

**Comment by vassilisimon** [comment]
Sorry, I still haven't had time. :(

**Comment by enessgokalp** [comment]
Do you continue to this pr?

**Comment by Bnyro** [comment]
> Do you continue to this pr?

He would probably have a tough time since a lot has changed in the last few months

**Pull request closed without merging**
