### PR TITLE
Auto Release on TG after GH Release.

### PR DESCRIPTION
**Pull request by rozari0**
You have to set a new Secret **TG_CID** with Value **libretube** and Add the bot in libretubes channel as well.

For example, check  https://t.me/abuneko/467

### CODE REVIEW

**Comment by Bnyro** [comment]
Why should we use a secret for `TG_CID` if it's `libretube` anyways?
And where is the bot referenced inside the code, is it the same as we're already using for debug builds? (I know we already have a token set, I just don't know what account it's from)

**Comment by rozari0** [comment]
> Why should we use a secret for `TG_CID` if it's `libretube` anyways?

I needed to check if that works correctly, that's why it's not hardcoded. 
 
> And where is the bot referenced inside the code

In line 57.

> is it the same as we're already using for debug builds?
 
Yes, it's the same. Check debug channel, there shouldn't be more than one bot. 🤷‍♂️

**Comment by Bnyro** [comment]
I assume https://t.me/LibreTubeBot needs writing permissions?

**Comment by rozari0** [comment]
> I assume https://t.me/LibreTubeBot needs writing permissions?

Not any extra permission needed. Just the default one.

**Pull request merged**
