### PR TITLE
Changed Save Icon in player view, added an About Section in the Settings, search view visual fixes

### PR DESCRIPTION
**Pull request by Bnyro**
1. Changed Save Icon in Player Fragment to a "Add  to List" icon 
2. Fixed black font of playlists in playlist search view
3. Removed video thumbnail border in search and channel fragment
4. Changed video thumbnail width (in search, playlist and channel fragment)
5. Changed channel icon size on search tab
6. Added an About Section in the Settings which opens the website in the users default browser
7. Added maximum video title length in Search View (if longer than 60 chars, the ones that are too much get replaced by "...") #153

### CODE REVIEW

**Comment by Bnyro** [comment]
Ready to become merged before sth else gets changed and merge conflicts occur :)

**Comment by Bnyro** [comment]
Tell me if I should change sth

**Comment by lilcheti** [comment]
Oh I'll merge it before anything else np

**Review by FireMasterK — APPROVED** [review]
Works as expected!

**Pull request merged**
