### PR TITLE
[Help section] Removed : Social Media from App

### PR DESCRIPTION
**Pull request by ARBoyGo**
As per Bnyro's notification, We would like to inform you that the LibreTube community on Reddit and Discord will be removed on May 1st, as it is no longer maintained by any of the LibreTube maintainers. These media platforms will no longer be affiliated with LibreTube.

Thank you.

Forgot to remove from app :)

### CODE REVIEW

**Comment by ARBoyGo** [comment]
When non-android Dev remove some code, This happens, Failed :)

**Comment by FireMasterK** [comment]
The app fails to compile, since there are some references in https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/activities/HelpActivity.kt too!

**Comment by ARBoyGo** [comment]
Oh my bad, Need to remove it.

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
Thank you!

**Pull request merged**
