### PR TITLE
Added onBack callback to handle back gesture when inside video's comment's replies

### PR DESCRIPTION
**Pull request by angolo**
#6010

### CODE REVIEW

**Comment by Bnyro** [comment]
Tested, this doesn't actually work.

**Comment by Bnyro** [comment]
Did you AI-generate this PR?

**Comment by angolo** [comment]
First of all, what does it make it AI Generated?
Second: I'm sorry, I tested it on my work pc with windows on an emulator with Android 34 and it worked, now building the project on my mac it seems it doesn't work

Third: yes, i forgot to remove the Log's import

**Comment by Bnyro** [comment]
> First of all, what does it make it AI Generated?
>
Sorry, apologies, I just made bad experiences with AI generated PRs recently.

> Second: I'm sorry, I tested it on my work pc with windows on an emulator with Android 34 and it worked, now building the project on my mac it seems it doesn't work
>
Have you tested if it works well without these changes on the emulator? If this change actually fixes the issue on some devices, it's still reasonable to merge.

**Comment by angolo** [comment]
I recovered my work pc, the emulator I used runs API 35, running the debugger it seems that on lower api's it is not registered / doesn't override the default onbackpressed behavior

**Comment by Bnyro** [comment]
I have tried debugging that issue and it seemed like the `onBackPressedDispatcher` isn't getting triggered when pressing the system back button in the replies fragment, but I've really no idea why...

**Pull request closed without merging**
