### PR TITLE
Autoplay and code formatting to satisfy ktlint

### PR DESCRIPTION
**Pull request by janisslsm**
This is an attempt at making the app automatically play the next video, it works fine but is this an acceptable solution?

@Bnyro @FireMasterK @lilcheti

### CODE REVIEW

**Comment by IceDBorn** [comment]
You should add a switch to the settings menu.

**Comment by Bnyro** [comment]
@IceDBorn Settings are already overfilled and I don't think that we would need a setting for that.

**Comment by janisslsm** [comment]
What about a switch in the player screen?

**Comment by Bnyro** [comment]
@janisslsm looks like a good idea :)

**Comment by lilcheti** [comment]
Should I merge this now?

**Comment by janisslsm** [comment]
> Should I merge this now?

Not yet, I haven't added a switch in the player yet. I've had a busy week

**Pull request closed without merging**
