### PR TITLE
Action version update

### PR DESCRIPTION
**Pull request by rozari0**
This will help to get rid of deprecated warning in workflow.

### CODE REVIEW

**Comment by Bnyro** [comment]
I tried bumping it once but the Telegram bot failed then, not sure what the issue was ...

**Comment by Bnyro** [comment]
I'll merge it and we see what happens!

**Comment by Bnyro** [comment]
Fair, Github Mobile doesn't allow me to, we'll need to wait until I return back home

**Comment by rozari0** [comment]
> I tried bumping it once but the Telegram bot failed then, not sure what the issue was ...

No error for me. 🤷‍♂️
ScreenShot

**Comment by FireMasterK** [comment]
It seems to be failing previously too and fails even now as well. It seems like it's running out of ram, and hence being killed :confused:

**Comment by FireMasterK** [comment]
Ugh, the script appears to be running a random binary: https://github.com/LibreTubeAlpha/Archive/blob/main/exec I can't find out what this does as there's no source code

**Comment by rozari0** [comment]
> It seems to be failing previously too and fails even now as well. It seems like it's running out of ram, and hence being killed 😕

Nope, tg uploader script forcely closing python after completing upload. I'm writing alternative one with pyrogram. I'll make a pr later.

**Comment by rozari0** [comment]
> Ugh, the script appears to be running a random binary: https://github.com/LibreTubeAlpha/Archive/blob/main/exec I can't find out what this does as there's no source code

This binary won't be needed anymore after merging #1669

**Pull request merged**
