### PR TITLE
Sign debug APK.

### PR DESCRIPTION
**Pull request by rozari0**
Recently I opened an [Issue](https://github.com/libre-tube/LibreTube/issues/1567). 

Now you have to set some env variable before merge it. : )

### CODE REVIEW

**Comment by Bnyro** [comment]
So I'll have to create a new release key to use for that and place it somewhere in the repo's files as well as settings the four secrets for it,, right?

**Comment by rozari0** [comment]
> So I'll have to create a new release key to use for that and place it somewhere in the repo's files as well as settings the four secrets for it,, right?

Not in files, just in secret.

**Comment by Bnyro** [comment]
Oh, right, just saw it in their docs, thanks!

**Comment by Bnyro** [comment]
Let's see whether it'll work x)

**Comment by rozari0** [comment]
> Let's see whether it'll work x)

I think it's working. :)

**Comment by Bnyro** [comment]
> I think it's working. :)
>
Aww, perfect ;)
I don't have TG anymore so it's up to you to test it :p

**Comment by Bnyro** [comment]
Thanks for your work on that <3

**Pull request merged**
